apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: traffic-simulator
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traffic-simulator
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # escala quando CPU média > 70%
